### ISSUE TITLE
Invoke-Sqlcmd2 -Verbose disabling -ErrorAction Stop

### ISSUE THREAD

**Issue by ubidev** [RamblingCookieMonster/PowerShell#16] opened 2016-06-10 19:45 UTC
Hi, while trying this script (v1.6.0)  to alleviate the original invoke-sqlcmd annoyances I encountered building a continuous delivery powershell script for a project, I encountered the following issue while handling errors.

The following will catch the error and is the expected behavior:
```
try
{
    $qry = 'SELECT COUNT(*) FROM InvalidTable'
    $result = Invoke-Sqlcmd2 -Query $qry -ServerInstance $instance -Database $db -ErrorAction stop
}
catch
{
    Write-Output 'ERROR'
    Break
}
```
But if I add the -verbose parameter, the catch block never fires !!!
```
try
{
    $qry = 'SELECT COUNT(*) FROM InvalidTable'
    $result = Invoke-Sqlcmd2 -Query $qry -ServerInstance $instance -Database $db -Verbose -ErrorAction stop
}
catch
{
    Write-Output 'ERROR'
    Break
}
```
Ironically, invoke-sqlcmd works in this case but -verbose does not display anything!!!
At first I thought it was caused by my usage of $ErrorActionPreference = 'stop' as  reported in the following [discussion](http://stackoverflow.com/questions/37006493/why-does-verbose-disable-the-use-of-erroractionpreference)

But even without it, and using -ErrorAction stop , the problem persists, which is abnormal to my knowledge.

Thanks in advance for your time and kudos for this amazing scripts library :)
UbiDev

**Comment by jeffchulg** [comment] 2016-08-25 08:03
Hi,
I think the problem is due to the following lines:

> #Following EventHandler is used for PRINT and RAISERROR T-SQL statements. Executed when -Verbose parameter specified by caller
>             if ($PSBoundParameters.Verbose)
>             {
>                 $conn.FireInfoMessageEventOnUserErrors=$true
>                 $handler = [System.Data.SqlClient.SqlInfoMessageEventHandler] { Write-Verbose "$($_)" }
>                 $conn.add_InfoMessage($handler)
>             }

[FireInfoMessageEventOnUserErrors](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.fireinfomessageeventonusererrors%28v=vs.110%29.aspx)

> When you set FireInfoMessageEventOnUserErrors to true, errors that were previously treated as exceptions are now handled as InfoMessage events.

So it seems to be an expected behaviour.
The reason why you set -Verbose is to output to a text file. I want to do the same.
Maybe it would be best to add a "-LogPath" option to Invoke-SQLCmd2 that will output everything in the provided path, wouldn't it ?

**Comment by ubidev** [comment] 2016-08-30 11:19
Good idea,! This LogPath/Variable alternative seems a better option especially if it is not possible to preserve the normal/expected behavior of -Verbose used in combination with -ErrorAction Stop 
Have a great day!

**Comment by RamblingCookieMonster** [comment] 2016-09-13 13:08
Sweet, looks like someone submitted a PR for this, changes from 714f233 are in place!

If anyone runs into an issue with the error handling being constrained to ` [System.Data.SqlClient.SqlException] ` let me know.

Cheers!

**Comment by RamblingCookieMonster** [comment] 2016-09-23 14:16
Hi!

Going to close this out, but FYI, moved [Invoke-SqlCmd2 to the SQLCollaborative org](https://github.com/sqlcollaborative/Invoke-SqlCmd2) if you have any follow-up.

Cheers!

**Closed by RamblingCookieMonster** 2016-09-23 14:16 UTC
